// <auto-generated />
using System;
using Ginder.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ginder.Infra.Migrations
{
    [DbContext(typeof(GinderDbContext))]
    partial class GinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ginder.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e4275ae-b5ed-4a16-a8c7-32d4c5cbd4f4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 6, 19, 1, 40, 10, 954, DateTimeKind.Unspecified).AddTicks(9157), new TimeSpan(0, -3, 0, 0, 0)),
                            ImagePath = "/Games/LeagueOfLegends.png",
                            Name = "League of Legends"
                        },
                        new
                        {
                            Id = new Guid("885c76df-b632-496e-a87f-98a5a362bd94"),
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 6, 19, 1, 40, 10, 954, DateTimeKind.Unspecified).AddTicks(9230), new TimeSpan(0, -3, 0, 0, 0)),
                            ImagePath = "/Games/WorldOfWarcraft.png",
                            Name = "World of Warcraft"
                        },
                        new
                        {
                            Id = new Guid("71833138-ba80-4851-bf9d-ff01ea572d88"),
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 6, 19, 1, 40, 10, 954, DateTimeKind.Unspecified).AddTicks(9238), new TimeSpan(0, -3, 0, 0, 0)),
                            ImagePath = "/Games/ShadowArena.png",
                            Name = "Shadow Arena"
                        });
                });

            modelBuilder.Entity("Ginder.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8413c17-63e7-491a-9eae-0489737e19ff"),
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 6, 19, 1, 40, 10, 953, DateTimeKind.Unspecified).AddTicks(5168), new TimeSpan(0, -3, 0, 0, 0)),
                            Idade = 20,
                            Name = "Admin Teste Player"
                        });
                });

            modelBuilder.Entity("Ginder.Domain.Entities.PlayerGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeriodTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGames");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fee6b24d-a74d-4391-ab0e-091d48762b6f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 6, 19, 1, 40, 10, 955, DateTimeKind.Unspecified).AddTicks(1582), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "Jogo pra me divertir",
                            GameId = new Guid("8e4275ae-b5ed-4a16-a8c7-32d4c5cbd4f4"),
                            PeriodTime = "Jogo aos finais de semanas",
                            PlayerId = new Guid("c8413c17-63e7-491a-9eae-0489737e19ff"),
                            Role = "Jogo na posição de ADC"
                        });
                });

            modelBuilder.Entity("Ginder.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6699c75-5f44-4029-a404-84ce8a3951c8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 6, 19, 1, 40, 10, 954, DateTimeKind.Unspecified).AddTicks(7998), new TimeSpan(0, -3, 0, 0, 0)),
                            Login = "admin",
                            Password = "123",
                            PlayerId = new Guid("c8413c17-63e7-491a-9eae-0489737e19ff")
                        });
                });

            modelBuilder.Entity("Ginder.Domain.Entities.PlayerGame", b =>
                {
                    b.HasOne("Ginder.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ginder.Domain.Entities.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ginder.Domain.Entities.User", b =>
                {
                    b.HasOne("Ginder.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
